### ISSUE TITLE
数据库无法访问

### ISSUE THREAD

**Issue by RGBli** [yunfeiyanggzq/miaosha#2]
我想查看一下表结构，但 application.properties 中写的数据库 IP 和 密码无法访问，方便提供一下建表语句吗？

**Comment by yunfeiyanggzq** [comment]
额，很久没有管这个项目了，我早就忘了，，，，不好意思哈

**Comment by RGBli** [comment]
哈哈哈哈没事儿，还是给我很多启发，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunfeiyanggzq/miaosha"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yunfeiyanggzq/miaosha] 数据库无法访问 (#2)





 
额，很久没有管这个项目了，我早就忘了，，，，不好意思哈
